openapi: 3.0.0
info:
  title: Products Management API
  contact: {}
  version: "1.0"
servers:
  - url: https://products-management-api.herokuapp.com/api/v1
    variables: {}
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register User
      operationId: RegisterUser
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUserRequest"
            example:
              name: billiam
              email: billiam@gmail.com
              password: secret
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login User
      operationId: LoginUser
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUserRequest"
            example:
              email: sally@gmail.com
              password: secret
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /products:
    post:
      tags:
        - Products
      summary: Create Product
      operationId: CreateProduct
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProductRequest"
            example:
              company: The Coca-Cola Company
              product: Sprite Original Citrus Flavor 2 liter
              description: Lemon Lime Carbonated Soft Drink
              price: 1.98
              unitPrice: 2.9
              taxRate: 5.45
              quantity: 35
              unit: fl oz
              packageType: Plastic Bottle
              upc: 049000050158
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
    get:
      tags:
        - Products
      summary: Get All Products
      operationId: GetAllProducts
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /products/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The product ID
    get:
      tags:
        - Products
      summary: Get Single Product
      operationId: GetSingleProduct
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false

    patch:
      tags:
        - Products
      summary: Update Product
      operationId: UpdateProduct
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProductRequest"
            example:
              company: The Coca-Cola Company
              product: Fanta Soda Pop
              description: Caffeine-Free Orange Soda Pop
              price: 1.94
              unitPrice: 9.7
              taxRate: 5.45
              quantity: 15
              unit: fl oz
              packageType: Plastic Bottle
              upc: 049000019162
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
    delete:
      tags:
        - Products
      summary: Delete product
      operationId: Deleteproduct
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
components:
  schemas:
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
        - name
        - email
        - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: bob
        email: bob@gmail.com
        password: secret
    LoginUserRequest:
      title: LoginUserRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: susan@gmail.com
        password: secret
    CreateProductRequest:
      title: CreateProductRequest
      required:
        - company
        - product
        - description
        - price
        - unitPrice
        - taxRate
        - quantity
        - unit
        - packageType
        - upc
      type: object
      properties:
        company:
          type: string
        product:
          type: string
        description:
          type: string
        price:
          type: number
        unitPrice:
          type: number
        taxRate:
          type: number
        quantity:
          type: number
        unit:
          type: string
        packageType:
          type: string
        upc:
          type: number
      example:
        company: The Coca-Cola Company
        product: Fanta Soda Pop
        description: Caffeine-Free Orange Soda Pop
        price: 1.94
        unitPrice: 9.7
        taxRate: 5.45
        quantity: 15
        unit: fl oz
        packageType: Plastic Bottle
        upc: 049000019162
    UpdateProductRequest:
      title: UpdateProductRequest
      required:
        - company
        - product
        - description
        - price
        - unitPrice
        - taxRate
        - quantity
        - unit
        - packageType
        - upc
      type: object
      properties:
        company:
          type: string
        product:
          type: string
        description:
          type: string
        price:
          type: number
        unitPrice:
          type: number
        taxRate:
          type: number
        quantity:
          type: number
        unit:
          type: string
        packageType:
          type: string
        upc:
          type: number
      example:
        company: The Coca-Cola Company
        product: Sprite Original Citrus Flavor 2 liter
        description: Lemon Lime Carbonated Soft Drink
        price: 1.98
        unitPrice: 2.9
        taxRate: 5.45
        quantity: 35
        unit: fl oz
        packageType: Plastic Bottle
        upc: 049000050158
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
  - httpBearer: []
tags:
  - name: Auth
    description: ""
  - name: Products
    description: ""
